### PR TITLE
Fix for #188

### PR DESCRIPTION
**Pull request by freddymartinez9**
This assumes you don't want more fixes than a simple check on the return code...

### CODE REVIEW

**Comment by freddymartinez9** [comment]
Sorry this first PR is using an outdated BUILD.md, everything should be synced and without merge conflicts now with https://github.com/freddymartinez9/onionshare/commit/c6160664c788895d7c9e19662c4be9fe7247a973

**Comment by micahflee** [comment]
Ooh thanks. Curious, why did you add python-central and python-socksipy as dependencies? It's always seemed to work fine for me without those (unless I already have them installed on my system and didn't notice).

**Comment by freddymartinez9** [comment]
Hi Micah,

No, that's an issue with my branch being out of sync with yours. Feel free
to just reject the PR and just copy and paste my code. (It would probably
be faster than going back and forward with branches).

Freddy

**Comment by micahflee** [comment]
Thanks!

**Pull request merged**
