### PR TITLE
Adding some changes to have old style

### PR DESCRIPTION
**Pull request by Kcchouette**
Following some change during new 2.3 release, the theme is now totally different from before.

The goal of this PR is to revert back to style in screenshot in PR https://github.com/micahflee/onionshare/pull/1140

### CODE REVIEW

**Comment by Kcchouette** [comment]
Hello
I saw your PR #1140  @SaptakS

Do you plan of doing it for "website" mode?

Because your changes seems to have broke this mode and I don't want to change your work
eg I would change for "website" mode:

```
.file-list div.d-flex {
  border-bottom: 1px solid #e0e0e0;
  justify-content: flex-start;
}
```

into 

```
.file-list tr {
  border-bottom: 1px solid #e0e0e0;
  justify-content: flex-start;
}
```

Cheers

**Comment by SaptakS** [comment]
@Kcchouette thanks for bringing this up. I would want to make the website mode have similar HTML as in the send html, basically replacing table layouting with flex layouts. If you want, feel free to add the similar changes from #1140 to this PR for website mode. It should be more or less same.

**Comment by Kcchouette** [comment]
Ok I'll try theses few days, I'll ping you again for checking

Thanks

**Comment by Kcchouette** [comment]
@SaptakS it was easier than I think so here the commit :fireworks:

**Comment by SaptakS** [comment]
Thanks! I will look into it by tomorrow!

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
