### PR TITLE
Add GUI unit tests

### PR DESCRIPTION
**Pull request by mig5**
This is a test script that tests the actual GUI . Previous incarnation existed as part of #404 but was abandoned

I'm currently using this script in Jenkins as part of a nightly build/test process against develop branch.

I'm opening this PR because it'd be nice to store this in the repo so I don't have to keep a copy of it on my Jenkins server (currently dropping it into the codebase as part of the process)?

But I don't want it to be in the 'test' folder because this test deliberately bootstraps Tor etc - I don't want that sort of test to potentially block either Deb packaging process, or Travis. So I'm putting it in dev_scripts/ as a helper.

You could run it locally even without xvfb to witness it 'in the flesh'. On Jenkins I run it through xvfb-run and it's beautiful.

I think the test names below give an indication of what happens: we start the GUI, wait for Tor to bootstrap, add a file to the file list and share it. We then test all manner of things (onion URL regex, various widgets hidden/shown/enabled/disabled at the right time, that the web server has literally closed its socket after stopping the share, etc etc)

It depends on the pytest extension 'pytest-ordering' which you can pip3 install.

```
jenkins@clou:/var/lib/jenkins/jobs/onionshare_nightly_gui_test/workspace$ xvfb-run py.test-3 -v dev_scripts/onionshare_gui_test.py 
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3 -- /usr/bin/python3
plugins: ordering
collected 21 items 

dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_gui_loaded_and_tor_bootstrapped PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_version_found PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_windowTitle_seen PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_download_container_is_hidden PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_settings_button_is_enabled PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_server_status_bar_is_visible PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_file_selection_widget_has_a_file PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_server_working_on_start_button_pressed PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_add_delete_buttons_now_disabled PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_settings_button_is_disabled PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_a_server_is_started PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_a_web_server_is_running PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_have_an_onion_service PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_have_a_slug PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_url_label_shown PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_have_copy_url_button PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_copy_url_button_click_shows_message PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_copy_url_button_click_clears_message PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_server_is_stopped PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_web_service_is_stopped PASSED
dev_scripts/onionshare_gui_test.py::OnionShareGuiTest::test_add_button_enabled_again PASSED

===================================================================================== 21 passed in 71.11 seconds ======================================================================================
```

I have actually written another one for testing persistent URLs, and I will do one for bridges too.. in which case, is it worth having a separate folder 'gui_tests' or does the clutter bother you?

### CODE REVIEW

**Comment by mig5** [comment]
I added a bunch more GUI unit tests: persistence, bridge and stealth tests. All of these, in addition to the main GUI unit test, are being run nightly via my Jenkins.

For this reason I've moved them into their own folder 'unit_tests'.

**Comment by micahflee** [comment]
This is awesome! So much of OnionShare is the GUI now, so being able to test it is great. I'm not bothered by having a separate `gui_tests` folder, too. I see that you're still adding new commits. Let me know when you think this is reasonably complete and I can review it.

**Comment by mig5** [comment]
I think this is reasonably complete now (though we should add more as we introduce more scenarios for use)

Current tests:

1) Main GUI test (tests that the GUI loads normally, that we can start a share, obtain valid Onion URL + slug, stop the share, ensure the web server stops too, and that various buttons/widgets are enabled/disabled/clickable/hidden/shown at the appropriate time)

2) Persistent URL test (tests that with persistence we can start a share, then stop, then start again, and we should have the same Onion URL/slug (implying that the private key/slug were saved to the json in between shares)

3) Stealth test (tests that we can start a share with stealth enabled and that we obtain a valid HidServAuth string, that we can click the Copy HidServAuth button and that the status bar shows the message and disappears as expected)

4) Bridge test (tests we can start a share with a mix of normal and obfs4 bridges enabled, and that those settings end up in the temporary torrc that's generated)

5) Auto-Stop timer test (tests we can set the auto-stop timer to 2 minutes from now, and that the share stops after those 2 minutes, with expected widget/messages shown)

6) Settings Dialog test (tests we can set various settings in the SettingsDialog, and that these new settings values are then reflected in the json after saving the dialog)

I am sure there are other scenarios/settings we could test, but this is so far about as comprehensive as I can make it so that it runs on my Jenkins server (e.g I can't test Tor Browser connection method etc there)

Note that if you try these, you need onionshare installed 'proper' (globally) or you get the 'Module onionshare not found' errors - the first part of the Jenkins test is ensuring we can build a .deb from develop branch and install it with dpkg -i.

I had limited success running the GUI tests on a Fedora AppVM and I'm not sure why (I blame X issues with Qubes maybe?). When running via xvfb-run on my Debian Jessie jenkins VPS, it works perfectly, so I'm happy enough with that. When using xvfb-run on my Fedora AppVM it just segfaults, so I gave up, it mattered more to me that it passes in Jenkins..

**Comment by mig5** [comment]
OK, six more tests added :) 

1) A test that actually downloads the share (making sure the share stops and that the file we download has the same text file inside the zip with the same contents!). 

2) another test of the same sort, but with stay_open setting enabled, so that we make sure a share did *not* stop after downloading the first share

3) a test of downloading the actual 'main' web page just to make sure some expected HTML content is present e.g there are no issues serving the main page.

4) two tests under System Tor mode (both control port and socket file)

5) A simple strings test that, with modified locale set to fr_FR-UTF-8, checks that some widgets are showing their French translation.

I feel that this is pretty comprehensive now! Bar the Tor Browser connection mode, and the UpdateCheck thread stuff, it tests most other features / settings currently available. 

[Latest Jenkins output](https://gist.githubusercontent.com/mig5/878c9898c8d4d1e9bb5af110ab84deb3/raw/138af19688ce8306135d656185c0a61ca25f2d95/gistfile1.txt)

Let me know if you want to 'test' these via Jenkins, I can give you an account on my Jenkins and let you fire the job.. I have it configured to retry the build a couple times if it fails or takes too long (e.g due to intermittent Tor timeout stuff). Overall the job takes about 15 minutes to run all the tests

**Comment by mig5** [comment]
I'm going to close this, and make a new branch/PR once the major ux-update has been merged into develop.

**Pull request closed without merging**
