### PR TITLE
GUI unit tests in both share and receive mode

### PR DESCRIPTION
**Pull request by mig5**

### CODE REVIEW

**Comment by mig5** [comment]
OK - here are some Share and Receive mode GUI unit tests!

I can run these perfectly like this:

(First you need some dependencies: `pip3 install pytest-faulthandler pytest-ordering pytest-qt` )

```
cd unit_tests
bash run_unit_tests.sh
```

(that runs them all in a row)

Or, I can run them manually with:

```
py.test-3 xxxxxxxx.py -vvv
```

At some stage I had a 'pytest' binary in my PATH and it failed with this. Maybe it was for Python 2.x.. Anyway, pytest-3 or py.test-3 (which is a symlink to the other on my system) works fine.

I couldn't get Travis to do the same. Wasn't an Xvfb issue, but some issue with py-test versions? I don't know... couldn't figure it out.

These tests all use --local-only mode, so they are super fast! The only one that takes about 1.5 minutes is deliberate: the timer test, where I test that the share/web server shuts down when the timer runs out.

You will see I test quite a range of things - presence of widgets at certain times etc, as well as actually downloading a share, testing the content of the web page, uploading in receive mode, testing that uploading the same file renames that file, etc etc. As well as public mode vs non-public mode.

Importantly I always test that the web server has stopped when it should have, to make sure we never introduce a regression that keeps a share open.

All sorts of stuff in these tests. Probably still some more to add. Maybe you want to give me CODEOWNERS access to unit_tests/ and I can add more over time? In any case, I will be running these every time I review a merge now :)

I had other tests but they are hard or impossible to accurately test in local mode (such as testing persistent URLs, that we get a valid .onion address, re-connecting to Tor after saving settings dialog, etc). Maybe those can be run via our Jenkins if you end up getting these ones to run via Travis.

**Comment by mig5** [comment]
For reference, here's my dumb error from Travis when trying to run some of those tests.

https://travis-ci.org/micahflee/onionshare/jobs/431804284

```
4.03s$ xvfb-run pytest unit_tests/onionshare_share_mode_download_test.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/_pytest/main.py", line 174, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/_pytest/config/__init__.py", line 583, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/__init__.py", line 628, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pytestqt/plugin.py", line 187, in pytest_configure
INTERNALERROR>     qt_api.set_qt_api(config.getini('qt_api'))
INTERNALERROR>   File "/home/travis/virtualenv/python3.6.6/lib/python3.6/site-packages/pytestqt/qt_compat.py", line 60, in set_qt_api
INTERNALERROR>     raise RuntimeError(msg)
INTERNALERROR> RuntimeError: pytest-qt requires either PySide, PySide2, PyQt4 or PyQt5 to be installed
```

*Obviously* PyQt5 is installed, it's part of install/requirements.txt which has been run! So it's a stupid error and I don't reproduce it locally..

Googling this turns up only 2 results, both related to Windows and not helpful.. oh well

**Comment by mig5** [comment]
I'm going to add a CommonTests class to move a lot of these tests into, which can be called from the other tests. That will reduce a lot of duplicate functions.

**Comment by micahflee** [comment]
Let me know when you're ready for me to review this PR. Excited to get this one merged.

**Comment by mig5** [comment]
@micahflee please go ahead and test `bash ./unit_tests/run_unit_tests.sh' in this branch! (noting the dependencies required, in my earlier comment).

All the tests have been refactored into a CommonTests class with lots and lots of abstraction for receive vs share mode. It's much more efficient now and less code/tests to maintain.

And they're still all passing their tests \o/

**Comment by mig5** [comment]
Ooh, uncovered an *intermittent* bug:

```
Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare/common.py", line 433, in get_available_port
    tmpsock.bind(("127.0.0.1", random.randint(min_port, max_port)))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare/onionshare.py", line 67, in choose_port
    self.port = self.common.get_available_port(17600, 17650)
  File "/home/user/git/onionshare/onionshare/common.py", line 436, in get_available_port
    raise OSError(e)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare_gui/threads.py", line 76, in run
    self.mode.app.choose_port()
  File "/home/user/git/onionshare/onionshare/onionshare.py", line 69, in choose_port
    raise OSError(strings._('no_available_port'))
OSError: Could not find an available port to start the onion service
```

I strongly doubt my machine is using *all* available ports.. maybe something for another ticket. I think I've reproduced this a handful of times this year.

The fact that it fails the tests means it's *not* a blocker here :)

**Comment by mig5** [comment]
P.S let me know if you want to re-send with just the one commit rather than all my trial and error above (git history noise). Or maybe you can 'squash' when you merge..

**Comment by micahflee** [comment]
When I run the tests in Ubuntu 18.04, a window pops up with the title "OnionShare" and it's empty, and it just stalls forever while trying to run the first test. Here's the output:

```
$ ./run_unit_tests.sh 
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.6.6, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
cachedir: ../.cache
PyQt5 5.10.1 -- Qt runtime 5.9.5 -- Qt compiled 5.9.5
rootdir: /home/user/code/onionshare, inifile:
plugins: qt-3.1.0, ordering-0.5, faulthandler-1.5.0
collected 25 items                                                                                                                                                                                         

onionshare_receive_mode_upload_test_public_mode.py::OnionShareGuiTest::test_gui_loaded 
```

I've tried a few things but haven't figured out where it's stalling at yet.

**Comment by mig5** [comment]
Damn, I was wondering if different OS/versions would cause an issue. It Just Works for me on Debian 9 (which I need to get off of anyway since we don't 'support' it anymore for 2.0).

I wonder if you run through xvfb-run or something if it makes a difference.

Is your Ubuntu machine in Qubes? Or don't you do dev in Qubes?

**Comment by micahflee** [comment]
I normally do dev in Fedora 28 in Qubes, but I've also been playing with an Ubuntu laptop that I've been doing dev on some recently, and that's what I'm working on now. I'll try in Fedora in Qubes, it will likely just work. But it would be nice for tests to work properly in Ubuntu if possible.

**Comment by mig5** [comment]
Definitely. COmparing your py.test-3's output at the start of your attempt, here are my PyQt etc versions

```
PyQt5 5.7 -- Qt runtime 5.7.1 -- Qt compiled 5.7.1
```

I suspect either the Qt version, or some issue with X, is the cause.. I'll try and switch to Fedora 28 today.

**Comment by micahflee** [comment]
Oh also, what do you think of this for integrating these tests more into the rest of the project? Make a new file `install/requirements-tests.txt`, with just the pip dependencies for the GUI tests. I think it should look like this:

```
atomicwrites==1.2.1
attrs==18.2.0
more-itertools==4.3.0
pluggy==0.7.1
py==1.6.0
pytest==3.8.1
pytest-faulthandler==1.5.0
pytest-ordering==0.5
pytest-qt==3.1.0
six==1.11.0
```

Then update the Tests section at the bottom of BUILD.md to include information on installing deps and running all the tests.

Also, I think the directory structure should change to be consistent. Right now we basically have two different test suites, the normal ones in `test`, and the GUI ones in `unit_tests`. What if we renamed `test` to `tests`, and renamed `unit_tests` to `tests_gui`?

We could even include a suite of Tor tests, that use the real Tor network, in `tests_tor`, and just not run those on Travis, but we can still run them manually if we want.

**Comment by mig5** [comment]
I'm up for all that, I wasn't sure if there were packaging implications for renaming the main test dir, since it seems Debian runs those tests during the .deb build process. Is it configurable?

The dark art in which Python/Debian figure out where the tests are has mystified me for some time..

Anyway, let's see if we can get them to even work everywhere first :)

**Comment by micahflee** [comment]
Just ran these tests on my Fedora 28 dev VM and it's so cool!

The first time I ran the tests, some of them failed, but I think this was due to the intermittent issue you found related to available ports. I ran it again and they all passed. This is great.

I also tried running these on Debian 9 (I had to `pip3 install sha3` first). They ran and got farther than on Ubuntu, but seemed to consistently run into the available port issue. In Debian, it even pops up a window with the error...

screenshot_2018-09-26_16-49-30

But I'm not too concerned about this because Debian 9 isn't supported. I'm going to create a debian-10 template though to test in.

For the timeout test, do you think we could change the timeout from 120 seconds to like 15 seconds? That should be plenty of time to test the timeout, considering we don't have to wait for an onion service to get created, and it would shave a lot of time off the tests.

So I guess the to do list is:

- Figure out how to get the tests running in Ubuntu 18.04
- Reduce time in the timeout (if you agree)
- Integrate tests more into the rest of the project

**Comment by mig5** [comment]
> The first time I ran the tests, some of them failed, but I think this was due to the intermittent issue you found related to available ports. I ran it again and they all passed. This is great.

I'm going to open a bug report about the port issue, as it's a very old regression I think I accidentally introduced. Basically we used to 'pass' this error in order to persist a 'while True' loop, meaning it probably used to eventually find a port. We now exit on the first clash, which is probably why we're seeing this more often. We're hitting a clash in the random search for a port, almost close to unrandomly...

 
> For the timeout test, do you think we could change the timeout from 120 seconds to like 15 seconds? That should be plenty of time to test the timeout, considering we don't have to wait for an onion service to get created, and it would shave a lot of time off the tests.

Yeah I wanted to do this - the problem is we currently hardcode a minimum 120s from 'now' in the actual OnionShare code (not the test). I originally did this because I didn't want a situation where users are making shares that terminate before the onion has a chance to set up (and then open tickets about it :P ). But since this is less likely on v3 (it's so fast to set up usually) I think we can remove this restriction.

I tried yesterday to set up on Fedora 28 but I had issues with pytest versions. I tried based on your requirements-tests.txt example... I'll try it again today if I have time (along with the shutdown timer 120s issue)

**Comment by mig5** [comment]
Did you do some magic on Fedora 28 re: the test dependencies?

I had to install a specific version of pluggy (0.6, as it needed >0.5 but < 0.7), and I get this fatal error:

```
===================================================================================================== ERRORS ======================================================================================================
_________________________________________________________________________ ERROR collecting unit_tests/onionshare_slug_persistent_test.py __________________________________________________________________________
ImportError while importing test module '/home/user/git/onionshare/unit_tests/onionshare_slug_persistent_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
onionshare_slug_persistent_test.py:15: in <module>
    from .commontests import CommonTests
commontests.py:2: in <module>
    import requests
/usr/lib/python3.6/site-packages/requests/__init__.py:43: in <module>
    import urllib3
/usr/lib/python3.6/site-packages/urllib3/__init__.py:8: in <module>
    from .connectionpool import (
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:11: in <module>
    from .exceptions import (
/usr/lib/python3.6/site-packages/urllib3/exceptions.py:2: in <module>
    from .packages.six.moves.http_client import (
E   ModuleNotFoundError: No module named 'urllib3.packages.six'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================= 1 error in 0.18 seconds ==============================
```

**Comment by mig5** [comment]
Also, mmm, complicated, we strip the seconds off the timeout for better UX, meaning the timeout really needs to be at least a minute in advance of the current time:

```
    def server_button_clicked(self):
        """
        Toggle starting or stopping the server.
        """
        if self.status == self.STATUS_STOPPED:
            if self.common.settings.get('shutdown_timeout'):
                # Get the timeout chosen, stripped of its seconds. This prevents confusion if the share stops at (say) 37 seconds past the minute chosen
                self.timeout = self.shutdown_timeout.dateTime().toPyDateTime().replace(second=0, microsecond=0)
                # If the timeout has actually passed already before the user hit Start, refuse to start the server.
                if QtCore.QDateTime.currentDateTime().toPyDateTime() > self.timeout:
                    Alert(self.common, strings._('gui_server_timeout_expired', QtWidgets.QMessageBox.Warning))
                else:
                    self.start_server()
```

Perhaps the shutdown timer test can be moved to be a non-local test (with Tor etc) so that it doesn't slow down local tests too much if you're in a hurry..

**Comment by mig5** [comment]
I have updated this branch to pass the `local_only` attribute down to `ServerStatus()` and `Mode()`. This is so that we can pass shorter timeouts purely for the sake of tests.

I've dropped the timer timeout accordingly so it's very short, but long enough to test properly.

I've renamed test to tests, unit_tests to tests_gui_local, updated the docs, added the tests dependency file for pip, updated paths in various other files for the renamed 'tests' dir, including .travis.yml

**Comment by mig5** [comment]
I've now added `tests_gui_tor/` too! These ones take much longer because they use bundled mode. But they are also more comprehensive - they test downloading/uploading via the .onion instead of via the webserver directly. 

They also test some extra things that rely on Tor/the UI being a bit slower, such as cancelling a share mid-startup (local-only is too fast to test this reliably).

There's also stealth mode test (parse the HidServAuth), a 'tor connection killed mid-share' test, and a more comprehensive persistent mode test in there.

Keep in mind these tests will periodically fail due to Tor timeouts (particularly on download/upload tests where the sockets might time out). Not a problem with the tests, just Tor. I've managed to get them *all* to run end to end successfully today via the run_unit_tests.sh script.

I feel like I could keep adding tests forever, but it would be good to draw an initial line at some stage at getting these into the codebase just so they persist across future feature branches. Another reason why I feel like it might be worthwhile to have 'codeownership' of these gui test dirs in order to push more tests more frequently into `develop` without the PR process (once we have it all nailed down for Ubuntu etc) what do you think?

**Comment by micahflee** [comment]
I'm happy to make you a code owner of the GUI tests -- or even of all the tests if you'd like. Want to add this to `.github/CODEOWNERS` in this PR, and you'll be a code owner when it gets merged?

```
# tests
/tests/ @mig5
/tests_gui_local/ @mig5
/tests_gui_tor/ @mig5
```

Also I agree with getting this merged sooner rather than later. Maybe even before fixing the problem with running them on Ubuntu... but let me take another stab at getting them working in Ubuntu first. If we can't get it, I'll merge this PR and we can just open an issue.

**Comment by micahflee** [comment]
Yup, when I run it with `--faulthandler-timeout 10` I actually can see the crash now:

```
$ py.test-3 onionshare_share_mode_download_test.py --faulthandler-timeout 10
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.6.6, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
PyQt5 5.10.1 -- Qt runtime 5.9.5 -- Qt compiled 5.9.5
rootdir: /home/user/code/onionshare, inifile:
plugins: qt-3.1.0, ordering-0.5, faulthandler-1.5.0
collected 27 items                                                                                                                                                                                         

onionshare_share_mode_download_test.py Timeout (0:00:10)!
Thread 0x00007f19135bd740 (most recent call first):
  File "/home/user/.local/lib/python3.6/site-packages/pytestqt/plugin.py", line 197 in _process_events
  File "/home/user/.local/lib/python3.6/site-packages/pytestqt/plugin.py", line 166 in pytest_runtest_call
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 196 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 216 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 222 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 617 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 175 in <lambda>
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 189 in __init__
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 175 in call_runtest_hook
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 155 in call_and_report
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 76 in runtestprotocol
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 62 in pytest_runtest_protocol
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 180 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 216 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 222 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 617 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 166 in pytest_runtestloop
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 180 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 216 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 222 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 617 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 143 in _main
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 105 in wrap_session
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 136 in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 180 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 216 in <lambda>
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 222 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/__init__.py", line 617 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 59 in main
  File "/usr/bin/py.test-3", line 11 in <module>
```

**Comment by micahflee** [comment]
Nice, I've solved the Ubuntu 18.04 issue (and honestly, I'm surprised we don't run into the same problem on other platforms). I'm making some new local commits myself, but I'll go ahead and approve them, and merge it into develop with my extra commits.

**Pull request merged**
