### PR TITLE
New design

### LINKED ISSUE #1073: New design for tabs
Adding tab support (#1064) is a major issue that includes a lot of refactoring, and it will also involve doing a lot of design work. This issue is for the design work, and will have a separate PR from the tabs themselves.

### PR DESCRIPTION
**Pull request by micahflee**
Resolves #1073 

New tab:

new_tab

Share mode:

share_files1
share_files2
share_files3

Receive mode:

receive_files1
receive_files2
receive_files3

Website mode:

website1
website2
website3

Chat mode:

chat1
chat2

### CODE REVIEW

**Comment by SamPatt** [comment]
@micahflee Looks great, nice work on this!

I tested each tab and only found one problem: I could not use the drag and drop functionality. Below is a gif of what I see.

onionsharedragdrop

I run Ubuntu 18.04 and tested on commit 218f9a6.

**Comment by micahflee** [comment]
Thanks for the reviews @SamPatt @mig5 ! I believe I just fixed it.

**Comment by micahflee** [comment]
I opened a separate issue for the tabs in macOS: #1156

**Comment by SamPatt** [comment]
> Thanks for the reviews @SamPatt @mig5 ! I believe I just fixed it.

Can confirm that drag and drop now works on Ubuntu 18.04.

**Pull request merged**
