### PR TITLE
When the server stops, resize the window to be small again instead of…

### PR DESCRIPTION
**Pull request by micahflee**
… having a huge downloads box.

Looks much better. Related to #632 but doesn't resolve it.

### CODE REVIEW

**Comment by mig5** [comment]
Unfortunately still looks a bit wonky on my Mac - the downloads container is much smaller, but the overall window is still much too big.

screen shot 2018-02-25 at 10 45 15 am

**Comment by micahflee** [comment]
You know, I was getting that at first too, but then I stopped being able to reproduce it and it was actually resizing the window. Hrm...

**Comment by micahflee** [comment]
I don't think we necessarily need to include this in the 1.3 release, too. I'm ok with having a few UI things that aren't perfect that we can put in a point release.

**Comment by mig5** [comment]
It seems to depend on where the app is placed on the screen - when it's mostly 'above' the dock, it's fine, but if it's to the far right, half 'past' the end of the dock, it will end up overlapping the dock.

**Comment by mig5** [comment]
I'm gonna close this, as I've realised #798 actually resolves this old issue.

**Pull request closed without merging**
