### PR TITLE
Major user experience update

### PR DESCRIPTION
**Pull request by micahflee**
This implements many of the amazing UX suggestions thanks to @glenn-sorrentino. Here are a few screenshots of the work-in-progress:

screenshot_2018-02-07_11-21-53
screenshot_2018-02-07_11-22-13
screenshot_2018-02-07_11-22-22
screenshot_2018-02-07_11-22-30
screenshot_2018-02-07_11-25-21
screenshot_2018-02-07_11-25-52

I'm making a PR but it's not quite ready for review. Here are the known issues:

- ~~Make sure auto-stop timer still works like it's supposed to, and stops the share when the timeout expires~~
- ~~Include re-design of client-side HTML so that it looks more like the OnionShare website that @glenn-sorrentino also designed~~
- ~~While the server is starting or started, you can still interface with the file list~~
- ~~After the server is started, there's a text wrapping issue with the "Anyone with this link" and URL labels~~

Feel free to test it and comment.

### CODE REVIEW

**Comment by micahflee** [comment]
Here is the UX spec: [OnionShare UX Spec.pdf](https://github.com/micahflee/onionshare/files/1701690/OnionShare.UX.Spec.pdf)

It also includes UX suggestions for #436 and #97 -- but because I waited 9 months before actually implementing, a lot of it is somewhat out-of-date. But it still contains a lot of really good stuff to work with.

**Comment by Baccount** [comment]
@micahflee The design is very nice, but the icons are low resolution on my MacBook retina display.

**Comment by micahflee** [comment]
Thanks @Baccount, I just added that to the list of things to fix in the PR description.

**Comment by glenn-sorrentino** [comment]
@Baccount Can you send a screenshot of the low-res images? If @micahflee doesn't have the assets, I'll get them created asap.

**Comment by edenemmanuel** [comment]
Love these screenshots. Looks far more intuitive than the also lovingly hand-crafted UI of before. 😄

**Comment by mig5** [comment]
@micahflee our old friend 'Squish Widget' is back, this time on the QLabel where persistent HidServAuth is in use, in the SettingsDialog (likely since you moved the auto-stop timer option there). I'll try and look at this today, as well as fix the auto-stop timer which has indeed broken

**Comment by Baccount** [comment]
@glenn-sorrentino Here is a photo with blue arrows pointing at the images that are low resolution.
image1

**Comment by Baccount** [comment]
@micahflee When I start onionshare with Tor 0.3.3 and some of the code in onion.py changed, the next generation onion url will get cut off. 
bug

**Comment by micahflee** [comment]
Check it out, I've redesigned the client-side HTML based on Glenn's design.

screenshot_2018-02-10_16-19-39

**Comment by micahflee** [comment]
Regarding retina displays and Qt5, here's some reading:
- https://doc.qt.io/qt-5/highdpi.html
- https://doc.qt.io/qt-5/qpainter.html#drawing-high-resolution-versions-of-pixmaps-and-images

**Comment by Baccount** [comment]
When I drag a large amount of files onto the app, the number gets cut off. Here is a photo showing the bug
issue

**Comment by micahflee** [comment]
I just redesigned the individual items within the file list. They look better now, and more importantly they prevent scrolling horizontally, and prevent the filename from being under the button.

Here's an example of a long filename with a both narrow and wide window:

screenshot_2018-02-10_18-16-56
screenshot_2018-02-10_18-17-08

@Baccount this resolves one of the issues you talked about. I haven't yet tested v3 onion services, but I also haven't set up my computer to actually use them yet either. Since it's not supported yet, I'm fine with leaving the UX elements of that to the PR that resolves #461.

**Comment by micahflee** [comment]
Just fixed the size count problem when dropping into the window too.

screenshot_2018-02-10_18-37-45

**Comment by Baccount** [comment]
The system and 3rd party app icons in the file lest are also low resolution "shown below
bug
". and thanks for fixing the size could bug.

**Comment by mig5** [comment]
I would suggest not to have any links to the Onionshare website (or any other website) - V3 URL or not - on the download page.

At least, there should not be any clickable links to external sites on clearnet or onion. If the onionshare.org site were to get hacked somehow, there could be a risk introduced of de-anonymising the user.

The user downloading the files, doesn't technically need to go installing the app.

And putting the onion addresses in the footer might only cause concern because they don't match the onion address the user is actually visiting. So I would just not have any links at all, just my 2c

**Comment by Baccount** [comment]
@micahflee 
1. The system and 3rd party app icons in the file lest are also low resolution "shown below".
bug

Implementing Retina display support as shown in your [post](https://github.com/micahflee/onionshare/pull/588#issuecomment-364708071) may fix this issue.
And thanks for fixing the size could bug.

**Comment by micahflee** [comment]
I've decided to remove supporting retina display as a goal for this PR, and instead opened a separate issue for it, #617.

**Comment by mig5** [comment]
@micahflee I'm going to hold off on review+merge until #619 and #620 are merged in by you, and possibly a fix implemented by you or someone for #604 (if you get nowhere with that one, you can always use my fix from #606)

**Comment by micahflee** [comment]
Yaaaaaay

**Comment by Baccount** [comment]
@glenn-sorrentino Did you finish making the high resolution assets? https://github.com/micahflee/onionshare/pull/588#issuecomment-363848089

**Comment by glenn-sorrentino** [comment]
I held off until we knew if QT supported retina. If you're ready for the
assets I'll get on it ASAP.

**Comment by glenn-sorrentino** [comment]
@Baccount I've got all of the assets created. I wasn't sure where @micahflee got the original icons from so I used an [open source icon set](https://useiconic.com/open) to create new ones. I still need to create the info icon - @mig5, where'd you find the one we're using now? One of the benefits of this set is that it has more consistency in the properties of the icons. An example can be seen in the "X" and the checkmark. Both share patterns for the angles used, which I think makes the icons feel more like they're from the same family.

I've also made the status icons smaller so that they're not so disproportionate with the size of the text. I've uploaded all of the icons to my [public Keybase folder](https://keybase.pub/glennsorrentino/onionshare-icons/), and have also forked the repo and added the icons to a [new branch](https://github.com/glenn-sorrentino/onionshare/tree/Icon-Updates/share/images).

Here's a side-by-side comparison of the updates:

zero state
ready
active
starting

**Comment by mig5** [comment]
@glenn-sorrentino these look great! Most of my icons I grabbed from https://www.iconsdb.com (yours look much nicer). The [i] icon, however, I think I got just via a google search - otherwise I see there's https://www.iconsdb.com/custom-color/info-2-icon.html - happy if you find a better version as you have above for the download indicators.

**Comment by Baccount** [comment]
@glenn-sorrentino Thank you so much the new icons look so much nicer on my Retina display. Again Thank you.

**Comment by glenn-sorrentino** [comment]
Just created a new info icon that I think is much more readable at small scale. Added to my repo and Keybase. 

info icon

**Comment by Baccount** [comment]
@glenn-sorrentino I downloaded your latest branch and compiled it, but when I open the app the only see of the  retina icons are visible.
bug

**Comment by glenn-sorrentino** [comment]
Did you do anything special to point to the @2x images?

A possible solution can be to only use the @2x images. If the CSS for those
images are sized to current widths, it'll be using source images that are
twice the size specified which should result with clear icons on retina
displays.

**Comment by Baccount** [comment]
@glenn-sorrentino  all I did was compile it from source.  I’m still seeing the 1x images

**Comment by glenn-sorrentino** [comment]
Makes sense. I'll make the base images twice the size... Let's see if that
works. I'll push those changes momentarily.

**Comment by glenn-sorrentino** [comment]
Okay, just pushed the changes.

**Comment by Baccount** [comment]
@glenn-sorrentino it looks like the status icon is cut off. 
bug

**Comment by Baccount** [comment]
@glenn-sorrentino Never-mine it works now something was wrong with GitHub still showing the old assets even with your newest branch. It seams to be resolved. The icons look great!

**Comment by Baccount** [comment]
The check icon is too large.
bug

**Comment by Baccount** [comment]
@glenn-sorrentino When I open the transparent icon in Affinity photo and then put it side by side with the app, the icon in AF looks sharper than it does in the app even though it is the same asset. It could be that we are missing a setting in Qt. These links explain how to enable retina support in Qt https://doc.qt.io/qt-5/highdpi.html
https://doc.qt.io/qt-5/qpainter.html#drawing-high-resolution-versions-of-pixmaps-and-images
issue

**Comment by glenn-sorrentino** [comment]
@Baccount for the checkmark, I'm using the same size as all of the other icons - It looks like something might be configured differently with this asset? Any luck so far with it?

**Comment by Baccount** [comment]
The checkmark issue is still occurring, but I think the bigger question is why Qt looks so much lower resolution than Xcode? I wonder if Xcode adds anti-aliasing to the image.
37496845-24df4de8-2872-11e8-9f55-e664054d9c99

**Comment by Baccount** [comment]
@mig5 can you take a look at https://github.com/micahflee/onionshare/pull/588#issuecomment-373552652 and https://github.com/micahflee/onionshare/pull/588#issuecomment-373500348 . I have not been able to fine a solution to fix these problems.

**Pull request merged**
