### PR TITLE
Bump pyinstaller requirements version

### LINKED ISSUE #451: Onionshare icon double bounce
When I open onion share the icon will bounce 2 times very fast. Onion share is the only app that has this issue. I attached a video showing the issue.
[bug.mov.zip](https://github.com/micahflee/onionshare/files/1073689/bug.mov.zip)

### PR DESCRIPTION
**Pull request by Baccount**
This fixes #451 and #533, @micahflee please compile the final macOS app with pyinstaller 3.3.1 to fix the bugs.

### CODE REVIEW

**Comment by mig5** [comment]
LGTM for both bugs mentioned, though I only tested building on macOS.

@micahflee I wonder if this newest version of Pyinstaller means the mentioning in https://github.com/micahflee/onionshare/blob/master/BUILD.md about 'pyinstaller bug prevents us from using Python 3.6' is obsolete? Worth trying with newer Python?

**Comment by Baccount** [comment]
@mig5 
I tested the compile with the following dependencies and it compiles without error.
PyInstaller: 3.3.1
Python: 3.6.4
Platform: Darwin-17.3.0-x86_64-i386-64bit

**Comment by micahflee** [comment]
@Baccount I ran into this problem in my Windows branch when I switch to python 3.6.4 as well, and fixed it in #540. I will test this, along with my commits from that branch, and see if I can get this working in OSX with python 3.6.4.

**Comment by micahflee** [comment]
#540 is now for both Windows and Mac, and it includes bumping the pyinstaller version (also, it upgrades python to 3.6.4 and Qt to 5.10.0). So this PR isn't necessary anymore.

**Pull request closed without merging**
