### PR TITLE
 Support meek_lite Pluggable Transports on Windows and Mac

### PR DESCRIPTION
**Pull request by irykoon**
According to https://lists.torproject.org/pipermail/tor-announce/2018-March/000153.html: Tor Browser 7.5.1 includes obfs4proxy (0.0.7), which supports meek_lite Pluggable Transports.

Therefore, undo: micahflee#649

It would be extremely helpful if someone could help me to test if this PR works.

Thank you!

### CODE REVIEW

**Comment by Baccount** [comment]
I built it from source and transferred obfs4proxy (0.0.7) into the .app and meek does not work but obfs4 connections do. @irykoon

**Comment by irykoon** [comment]
Baccount:
> I built it from source and transferred obfs4proxy (0.0.7) into the .app and meek does not work but obfs4 connections do. @irykoon 

Thank you for testing, @Baccount !

I am not sure what could be the next step for me because I am not able
to really test it on Windows or MacOS.

I may have to wait others to do further contribution on this now.

**Comment by Baccount** [comment]
@irykoon let’s see if @mig5 can fix the issue.

**Comment by mig5** [comment]
Haven't tested this yet but I can already see the updated obfs4proxy 0.07 from latest Tor Browser, is working perfectly fine with a typical meek_lite torrc generated by OnionShare.

```
Miguels-MacBook-Pro:~ miguel$ /Applications/TorBrowser.app/Contents/MacOS/Tor/tor.real -f torrc
Mar 15 11:21:35.888 [notice] Tor 0.3.2.10 running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2n, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Mar 15 11:21:35.889 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Mar 15 11:21:35.889 [notice] Read configuration file "/Users/miguel/torrc".
Mar 15 11:21:35.893 [notice] Scheduler type KISTLite has been enabled.
Mar 15 11:21:35.893 [notice] Opening Socks listener on 127.0.0.1:59824
Mar 15 11:21:35.894 [notice] Opening Control listener on /var/folders/dg/phy00_qj4nqd475xvyfq3zx00000gn/T/tmp3tfcchm4/control_socket
Mar 15 11:21:35.000 [notice] Parsing GEOIP IPv4 file /Applications/TorBrowser.app/Contents/Resources/TorBrowser/Tor/geoip.
Mar 15 11:21:36.000 [notice] Parsing GEOIP IPv6 file /Applications/TorBrowser.app/Contents/Resources/TorBrowser/Tor/geoip6.
Mar 15 11:21:36.000 [notice] Bootstrapped 0%: Starting
Mar 15 11:21:36.000 [notice] Starting with guard context "bridges"
Mar 15 11:21:36.000 [notice] Delaying directory fetches: No running bridges
Mar 15 11:21:38.000 [notice] Bootstrapped 5%: Connecting to directory server
Mar 15 11:21:38.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Mar 15 11:21:41.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Mar 15 11:21:42.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Mar 15 11:21:42.000 [notice] new bridge descriptor 'TorLandMeek' (fresh): $B9E7141C594AF25699E0079C1F0146F409495296~TorLandMeek at 0.0.2.0
Mar 15 11:21:44.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
Mar 15 11:21:55.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Mar 15 11:21:56.000 [notice] Bootstrapped 40%: Loading authority key certs
Mar 15 11:21:56.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Mar 15 11:21:56.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6197, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of exit bw = 0% of path bw.)
Mar 15 11:21:57.000 [notice] Bootstrapped 50%: Loading relay descriptors
Mar 15 11:22:40.000 [notice] Bootstrapped 55%: Loading relay descriptors
Mar 15 11:22:40.000 [notice] Bootstrapped 63%: Loading relay descriptors
Mar 15 11:22:41.000 [notice] Bootstrapped 69%: Loading relay descriptors
Mar 15 11:22:41.000 [notice] Bootstrapped 77%: Loading relay descriptors
Mar 15 11:22:41.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Mar 15 11:22:41.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Mar 15 11:22:43.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Mar 15 11:22:47.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Mar 15 11:22:47.000 [notice] Bootstrapped 100%: Done
```

So I'll test this PR soon and see if there are any issues.

**Comment by mig5** [comment]
This combined with the PR from #670 is working perfectly for me on Mac, for both Azure and Amazon meek_lite options.

I'll test in Windows soon but this is looking fine.

**Comment by Baccount** [comment]
@irykoon It works fine on my end, I'm running macOS 10.13.3 (17D102)

**Comment by mig5** [comment]
Working fine on Windows too.

**Comment by irykoon** [comment]
> We may remove or modify the CHANGELOG entry

Thank you, @mig5 ! 

Done :)

**Comment by micahflee** [comment]
Nice, I've reviewed the code and this looks great. I will soon test both this and #670 today (don't have convenient Win/Mac dev environments with me at the moment), and hopefully merge them both at the same time.

**Comment by mig5** [comment]
Hi @irykoon ! We've been busy making a *lot* of changes that have been merged into the `develop` branch. Unfortunately, this means your change now conflicts with what's in `develop` branch. Sorry it took so long to look at merging it in.

Do you want to merge the current `develop` branch into your branch? This will cause some conflict errors for you reported by git, but these can be fixed by editing the files manually. After that, we can merge in the change.

**Pull request merged**
