### PR TITLE
Prettier ASCII art

### PR DESCRIPTION
**Pull request by micahflee**
Before:

Screenshot_2021-04-25_19-23-41

After:

Screenshot_2021-04-25_19-24-03

### CODE REVIEW

**Comment by SaptakS** [comment]
This is how it appears in my debian system:
Screenshot from 2021-04-26 12-42-56

**Comment by SaptakS** [comment]
Seems like for some reason, [this](https://github.com/micahflee/onionshare/pull/1334#issuecomment-826572243) was an issue with my tmux config and nothing to do with debian terminal in general.

**Review by SaptakS — APPROVED** [review]

**Comment by micahflee** [comment]
Here are the changes:

- Adorable new ASCII art that is also smaller and more compact, and I decided to give it a background color so that it will look the good on both light and dark terminal backgrounds
- The version string gets displayed properly with the right amount of spaces after it regardless of how many characters the version takes up
- ASCII art banner is shown in both CLI and GUI when launching from the terminal

Screenshot_2021-04-28_19-23-56

**Comment by micahflee** [comment]
Screenshots from macOS with dark and light (default) terminals

Screen Shot 2021-04-28 at 4 57 23 PM

Screen Shot 2021-04-28 at 4 56 44 PM

**Comment by micahflee** [comment]
Screenshot at 2021-04-28 20-25-02

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
