### PR TITLE
Website sharing

### PR DESCRIPTION
**Pull request by hiromipaw**
Hi,

I have managed to find time to develop this feature also for the gui component.
There are some adjustments that I will still need to do, but I just wanted to show you the functionality. 
I had started t code this before the new developments, so some of the ui is actually a bit funky at the moment, but I am not too concerned about that since we would probably need to reconsider a few things about this website publishing mode anyways.

Looking forward to see what you think about this.

### CODE REVIEW

**Comment by micahflee** [comment]
Thank you for working on this, I'm very excited about this feature! I'm testing it out now and here are some initial thoughts:

**I'd like website mode to also include nice OnionShare-branded directory listings when loading a folder that doesn't include a `index.html`.** (Don't worry about the design though, just any form of directory listing is good to begin with.)

This way you can, for example, use website sharing and point it to a folder of photos or videos or documents or something, and Tor Browser users can go in and download only the individual files they care about.

Right now if you use website mode on a folder without an `index.html`, it throws an exception and returns a 500 Internal Server Error in the browser:

```
$ ./dev_scripts/onionshare --local-only --website .
OnionShare 2.0.dev2 | https://onionshare.org/
Compressing files.
 * Running on http://127.0.0.1:17629/ (Press CTRL+C to quit)

Give this address to the recipient:
http://127.0.0.1:17629/smartness-chirping

Press Ctrl+C to stop the server
[2019-01-27 10:35:55,636] ERROR in app: Exception on /smartness-chirping [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/code/onionshare-hiro/onionshare/web/website_mode.py", line 33, in index
    return path_logic(slug_candidate)
  File "/home/user/code/onionshare-hiro/onionshare/web/website_mode.py", line 88, in path_logic
    f = open(page, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/code/onionshare-hiro/index.html'
127.0.0.1 - - [27/Jan/2019 10:35:55] "GET /smartness-chirping HTTP/1.1" 500 -
127.0.0.1 - - [27/Jan/2019 10:35:55] "GET /favicon.ico HTTP/1.1" 404 -
```

**We should figure out how the GUI should look.**

Right now website mode looks similar to share mode:

screenshot from 2019-01-27 10-40-13

But I think website mode is fundamentally different.

Instead of dragging files in to make up the website, it's probably more appropriate to have a single browser button, and to browse to select a folder to share. (This is already implemented in the Settings dialog, when you browse to choose the receive mode folder, it's pretty simple to do in Qt.)

And similarly, the history widget is also totally different than share or receive mode -- really, I think the useful info in the history widget would be web server logs, so each history item could show the timestamp, http method, path, and return code, and maybe other info like the file size: `Jan 27 2019 10:39:19 | GET /index.html | 200` -- only it could be formatted nicely with colors and stuff since it's a Qt GUI.

**We should figure out how to deal with the slug, and public mode.** By default, public mode is turned off in the settings, which means the URLs look like `http://[something].onion/[slug]`. To prevent an attacker who learns the onion address from guessing the slug, OnionShare keeps track of the number of 404 errors, and if there are 20 of them, it automatically stops the server. (When public mode is on, then there is no slug, the URL is `http://[something].onion/, and the number of 404 errors doesn't matter).

I discovered, when trying to use website mode with public mode off on the [onionshare-website](https://github.com/micahflee/onionshare-website) static website, that there are over 20 assets and when I load it in a browser even once, it automatically makes over 20 404 errors, and stops the server:

screenshot from 2019-01-27 10-51-01

Another problem with using it with public mode off is that the slug will break absolute links, and only relative links will work. For example, if the website include an image like ``, this will be a broken image if there's a slug, since the link should really be to `/[slug]/images/header.jpg` for it to work. (I think this is why I had so many 404 errors, because the images and css and stuff were absolute links and not relative ones.)

All of this leads me to think that website sharing mode will just simply work better with public mode disabled. But, what if the website your sharing (or files with directory listing) are private, and you don't want public mode to be enabled? I'm not sure exactly but I think we should give this some thought and figure out how to proceed.

**Right now, subfolders seem to be broken.** When I share the `onionshare-website` folder in website mode (with public mode on, to make things simpler without a slug or a limit on 404 errors), I can't access resources in subfolders. See all of the 404 errors:

```
$ ./dev_scripts/onionshare --website ../onionshare-website
OnionShare 2.0.dev2 | https://onionshare.org/
Setting up onion service on port 17638.
Compressing files.
 * Running on http://127.0.0.1:17638/ (Press CTRL+C to quit)

Give this address to the recipient:
http://ung2jvprmnz2j4qf.onion

Press Ctrl+C to stop the server
127.0.0.1 - - [27/Jan/2019 10:58:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2019 10:58:31] "GET /assets/css/reset.css HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:31] "GET /assets/css/style.css HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:32] "GET /assets/img/logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:32] "GET /assets/img/windows-logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:32] "GET /assets/img/apple-logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:33] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:33] "GET /assets/img/ubuntu-logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:33] "GET /assets/img/fedora-logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:34] "GET /assets/img/linux-logo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:34] "GET /assets/img/gizmodo.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:34] "GET /assets/img/wired.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:58:35] "GET /assets/img/tor.png HTTP/1.1" 404 -
```

And here's what the website itself looks like:

screenshot from 2019-01-27 10-59-14

When I try accessing a specific resource, like `/assets/css/style.css`, I get a 404 error (and, in addition, the 404 error page tries to load some OnionShare resources itself in the `/static` folder, and those are 404 too).

```
127.0.0.1 - - [27/Jan/2019 10:59:50] "GET /assets/css/style.css HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:59:51] "GET /static/css/style.css HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:59:52] "GET /static/img/logo_large.png HTTP/1.1" 404 -
127.0.0.1 - - [27/Jan/2019 10:59:52] "GET /static/img/favicon.ico HTTP/1.1" 404 -
```

screenshot from 2019-01-27 11-01-05

But anyway, this is a great start, and I'm excited about it. I added the 2.1 milestone on it. After 2.0 is released, I'd be into working with you on finishing this feature.

**Comment by holantonela** [comment]
Thanks for this review @micahflee! 

Some throughs:
- I think the drag and drop is a nice feature and we can keep it. We could have an `Select`  link to search into local folders too. Something like:

publish

- Once the user uploads the files, could be nice if the entire windows become a `Sharing Website` one. In that way, we focus the user flow to the action they intended.
- I like the idea of having a UI feedback for current visitors. In the same way, we have it running for downloaded documents; we could have a [eye/view] icon to render it. An idea here:

publish-sharing

- If the uploaded folder must follow any structure to work or if we need to advise about relative links, this is something we should include in some way. An onion link to docs seems a plausible idea.

I'm excited that you included it for 2.1. Looking forward to it!

**Comment by micahflee** [comment]
This PR will resolve #791 (just want to link these two issues in GitHub).

**Comment by zoltankonder** [comment]
Slow down @micahflee! You will not replace hidden services with OnionShare no matter how excited you are! This proposed feature is totally unnecessary and I'm fully against it. Just how I was against that you and EFF stolen the code of DeadDrop which is written by Aaron Swartz after his death. I don't want to hear from you again that—“I'm very excited about this feature”—because it's pisses me off! Replacing tor hidden services is NOT an option better you forget it very fast!

**Comment by mig5** [comment]
I'm going to close this just because the subsequent work ended up in a new PR #961

**Pull request closed without merging**
