### PR TITLE
Add language dropdown

### LINKED ISSUE #690: Choose language dropdown
Right now, OnionShare tries to detect the language of the operating system and uses that if available, and otherwise falls back to English. Instead, there should be a `language` setting, and it should default to the OS language, but should be configurable in the settings.

I've learned that some non-English users often set their OS language to English because of bad translations in a bunch of applications, and then manually change the language to their native language in specific applications. I'd like these users to be able to manually choose OnionShare's language.

### PR DESCRIPTION
**Pull request by micahflee**
Resolves #690.

This was more interesting to implement than I expected.

The Settings object now has a `available_locales` dict that lists out all available locales, mapped to the language name in that language. I decided that it makes more sense, and is more usable, to not localize the language names themselves. This way the language dropdown will include "Русский" instead of "Russian" and "Español" instead of "Spanish".

When you open settings and change your language, it changes the setting immediately but you have to restart OnionShare before it can change all of the strings in all of the existing widgets. So it displays a notice to you that you have to restart OnionShare, but it displays this notice in the language you're _switching_ to. (You'll have to add a "gui_settings_language_changed_notice" string to some other language to test this, since that string is only in English so far.)

### CODE REVIEW

**Comment by micahflee** [comment]
Ok, the local GUI tests pass!

The tor GUI tests are totally broken though. But the refactoring of the tests that I did in #798 should actually (mostly) fix them, though I haven't attempted a merge yet.

So I think I'll try to finish #798 first, and when that gets merged into develop, I'll then merge develop into here and finish fixing the tests. So, go ahead and and review this, but don't merge quite yet.

**Comment by mig5** [comment]
I tried switching to French and OnionShare crashed with the below error:

```
user@onionshare:~/git/onionshare$ ./dev_scripts/onionshare-gui --debug
OnionShare 2.0.dev | https://onionshare.org/
[Oct 01 2018 12:05:25 PM] Onion.__init__
[Oct 01 2018 12:05:25 PM] OnionShare.__init__
[Oct 01 2018 12:05:25 PM] OnionShareGui.__init__
[Oct 01 2018 12:05:25 PM] Web.__init__: is_gui=True, mode=share
[Oct 01 2018 12:05:25 PM] ShareModeWeb.__init__
[Oct 01 2018 12:05:25 PM] Web.__init__: is_gui=True, mode=receive
[Oct 01 2018 12:05:25 PM] ReceiveModeWeb.__init__
[Oct 01 2018 12:05:25 PM] Uploads.__init__
[Oct 01 2018 12:05:25 PM] TorConnectionDialog.__init__
[Oct 01 2018 12:05:25 PM] TorConnectionDialog.start
[Oct 01 2018 12:05:25 PM] TorConnectionThread.__init__
[Oct 01 2018 12:05:25 PM] TorConnectionThread.run
[Oct 01 2018 12:05:25 PM] Onion.connect
[Oct 01 2018 12:05:25 PM] TorConnectionDialog._connected_to_tor
[Oct 01 2018 12:06:28 PM] OnionShareGui.open_settings
[Oct 01 2018 12:06:28 PM] SettingsDialog.__init__
[Oct 01 2018 12:06:28 PM] Settings.__init__
[Oct 01 2018 12:06:28 PM] Settings.load
[Oct 01 2018 12:06:28 PM] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
[Oct 01 2018 12:06:28 PM] SettingsDialog._update_autoupdate_timestamp
[Oct 01 2018 12:06:28 PM] SettingsDialog.connection_type_socket_file_toggled
[Oct 01 2018 12:06:28 PM] SettingsDialog.authenticate_no_auth_toggled
[Oct 01 2018 12:06:41 PM] SettingsDialog.save_clicked
[Oct 01 2018 12:06:41 PM] SettingsDialog.settings_from_fields
[Oct 01 2018 12:06:41 PM] Settings.__init__
[Oct 01 2018 12:06:41 PM] Settings.load
[Oct 01 2018 12:06:41 PM] Settings.load: Trying to load /home/user/.config/onionshare/onionshare.json
Traceback (most recent call last):
  File "/home/user/git/onionshare/onionshare_gui/settings_dialog.py", line 843, in save_clicked
    settings = self.settings_from_fields()
  File "/home/user/git/onionshare/onionshare_gui/settings_dialog.py", line 987, in settings_from_fields
    settings.set('use_autoupdate')
TypeError: set() missing 1 required positional argument: 'val'
Aborted
```

**Comment by mig5** [comment]
I pushed a fix for the above - it seems `settings.set()` is not true/falsy implicitly anymore, so needed a couple settings' values to be explicitly set.

I also added a French translation through the course of testing it. Works well!

One other thing: CLI is currently broken, I'm looking at that now:

```
user@onionshare:~/git/onionshare$ ./dev_scripts/onionshare --debug BUILD.md 
Traceback (most recent call last):
  File "./dev_scripts/onionshare", line 28, in <module>
    onionshare.main()
  File "/home/user/git/onionshare/onionshare/__init__.py", line 37, in main
    common.load_settings(config)
UnboundLocalError: local variable 'config' referenced before assignment
```

**Comment by mig5** [comment]
@micahflee what do you think of this patch to onionshare/__init__.py?

https://gist.github.com/mig5/ac809baa9592399806babf093b566f07

Basically it's a slight revert: we go back to loading the 'default' settings and therefore the default locale strings early, before we parse options (which might include a --config flag for an alternate json file that has some other locale).

If we end up loading that alternate --config and start a share, we 'reload' the strings right after, and subsequent log messages etc are printed in that potentially alternate locale. Here's an example where my 'main' onionshare.json is english, but I pass a French one:

```
user@onionshare:~/git/onionshare$ ./dev_scripts/onionshare --debug BUILD.md --config ~/.config/onionshare/fr.json 
OnionShare 2.0.dev | https://onionshare.org/
[Oct 01 2018 13:10:06] Web.__init__: is_gui=False, mode=share
[Oct 01 2018 13:10:06] ShareModeWeb.__init__
[Oct 01 2018 13:10:06] Onion.__init__
[Oct 01 2018 13:10:06] Onion.connect
[Oct 01 2018 13:10:06] OnionShare.__init__
[Oct 01 2018 13:10:06] OnionShare.set_stealth: stealth=False
[Oct 01 2018 13:10:06] OnionShare.start_onion_service
[Oct 01 2018 13:10:06] Onion.start_onion_service
Setting up onion service on port 17622.
[Oct 01 2018 13:10:06] Onion.start_onion_service: key_type=ED25519-V3
[Oct 01 2018 13:10:16] Settings.save
[Oct 01 2018 13:10:16] Settings.save: Settings saved in /home/user/.config/onionshare/fr.json
Préparation des fichiers à partager.
[Oct 01 2018 13:10:16] ShareModeWeb.set_file_info
[Oct 01 2018 13:10:16] Web.start: port=17622, stay_open=False, public_mode=False, persistent_slug=
[Oct 01 2018 13:10:16] Web.generate_slug: persistent_slug=
[Oct 01 2018 13:10:16] Web.generate_slug: built random slug: "subtitle-retype"
 * Running on http://127.0.0.1:17622/ (Press CTRL+C to quit)

Donnez cette URL à la personne qui doit recevoir le fichier :
http://ircks3wshapeph4ddyr7r6pvxn2v2xog2oidsyhfpjkj5p6asa4tl6id.onion/subtitle-retype

Ctrl-C arrête le serveur
```
The only downside here is that if the user passes `--help`, they only ever get to see the information in English because we've only been able to load the default locale strings up til this point:

```
user@onionshare:~/git/onionshare$ ./dev_scripts/onionshare --debug BUILD.md --config ~/.config/onionshare/fr.json  --help
OnionShare 2.0.dev | https://onionshare.org/
usage: onionshare [-h] [--local-only] [--stay-open] [--shutdown-timeout <int>]
                  [--stealth] [--receive] [--config config] [--debug]
                  [filename [filename ...]]

positional arguments:
  filename                  List of files or folders to share

optional arguments:
  -h, --help                show this help message and exit
  --local-only              Don't use Tor (only for development)
  --stay-open               Keep sharing after first download
  --shutdown-timeout <int>  Stop sharing after a given amount of seconds
  --stealth                 Use client authorization (advanced)
  --receive                 Receive shares instead of sending them
  --config config           Custom JSON config file location (optional)
  --debug                   Log OnionShare errors to stdout, and web errors to
                            disk
```

I can't think of a way around that. Parsers depend on strings, strings depend on settings object, and settings object depends on --config having been parsed or else uses default.

**Comment by mig5** [comment]
OK, so it's the same sort of story for the GUI - you actually had sort of avoided your catch-22 there already by loading the settings without the config object passed in. I add a reload of said settings/locale after we parse for the presence of `---config`. This patch fixes both CLI and GUI

https://gist.github.com/mig5/ac809baa9592399806babf093b566f07

However even here, the Settings Dialog save bug/traceback still occurs, so indeed is probably a separate bug, I might fix that myself directly if it's simple (like the earlier bugs), just wanted you to review this more complex fix first rather than commit it myself.

**Comment by micahflee** [comment]
Wow, thanks! I think your approach is totally fine.

I'm too concerned about the custom config edge case, because most likely if you're using custom OnionShare configs, you made them yourself so they're already using you default language.

Feel free to take up where I left off if you'd like. Otherwise I can try fixing it in the next few days.

**Comment by micahflee** [comment]
Wow, thanks! I think your approach is totally fine.

I'm too concerned about the custom config edge case, because most likely if you're using custom OnionShare configs, you made them yourself so they're already using you default language.

Feel free to take up where I left off if you'd like. Otherwise I can try fixing it in the next few days.

**Comment by micahflee** [comment]
Ok, I just merged in `develop` and also `780_improved_ui`, fixed the merge conflicts, and now all the local GUI tests pass again.

**Comment by mig5** [comment]
Ha - just merged #798 !

**Comment by mig5** [comment]
Local tests are working for me, and the actual intended functionality of this PR (language drop down) is still working too.

Is it worth therefore just merging this, and keeping the Tor test refactoring separate so it can be its own PR? What do you think?

**Comment by micahflee** [comment]
Yeah, let's merge and fix the Tor tests in a separate PR.

**Pull request merged**
