### PR TITLE
Time to close

### PR DESCRIPTION
**Pull request by choltz95**
Implement enhancement #177 
- added timer daemon in helpers.py (close_after_seconds())
- added thread instance variable in onionshare class (t_cas)
- added QLineEdit field to gui options alongside previous checkbox
- stay_open bool -> integer; false -> 0 & empty gui field + checkbox = no time limit

### CODE REVIEW

**Comment by micahflee** [comment]
(Sorry I'm so late.) Wow thanks for implementing this. Testing it now.

**Comment by micahflee** [comment]
This doesn't quite implement what I have in mind for #177. Normally, onionshare closes the server as soon as the download completes. The `--stay-open` flag means don't do that, keep the server open for longer.

The feature in #177 is basically: close the server as soon as the download completes, or after X time, whichever comes first. So you onionshare a file with a time limit of 2 hours, and then send someone the link. If they don't click it within 2 hours, the server stops. If they do click it, the server closes as soon as the download finishes.

If you run onionshare with `--stay-open 2` using the code in this PR (to stay open for 2 hours), and the person on the other end immediately downloads the file, the server won't automatically close, and will in fact remain open for almost 2 hours more before it closes.

Would you be into changing it to work like that? So `--stay-open` would remain a bool and work how it used to, but adding a new flag `--shutdown-timeout` to allow for automatically shutting down the server after the timeout ends?

Also, I think the GUI can be improved. When I open the GUI the window it looks like this:

snapshot1

I think it should be something like:

```
☑ Stop sharing when download completes
☑ Stop sharing after [120] minutes
```

The checkbox would mean that `shutdown-timeout` is active, and the `[120]` could be a text field. If the server is currently running, that field be going down automatically, so you can see how long before the server stops.

**Comment by choltz95** [comment]
These should be easy things to fix. I will make the changes in the next few days.

**Comment by micahflee** [comment]
Thanks for implementing this @choltz95 but @mig5 has begun a new implementation that's farther along in #473, so I'm going to close this one.

**Pull request closed without merging**
