### PR TITLE
Add [da] translations

### PR DESCRIPTION
**Pull request by scootergrisen**
Perhaps add info about this in https://github.com/micahflee/onionshare/wiki/Translating so translators can know they need to translate this file also.
Or even better add the strings to the .json translations files so alle strings are in one place.

### CODE REVIEW

**Comment by mig5** [comment]
I'm not sure we can inject strings from the json into the nautilus file, though perhaps it could be template-ized somehow and created on intallation... @micahflee ?

Good idea re: the wiki - anyone can edit the wiki, feel free to add your improvements! :)

**Comment by scootergrisen** [comment]
I don't seem to have permission to edit wiki
Here i see Edit button top right: https://github.com/audacity/audacity/wiki
Here i see no Edit button: https://github.com/micahflee/onionshare/wiki/Translating

**Comment by mig5** [comment]
OK, strange, it used to be editable by any Github user I thought (or at least contributor)

**Comment by micahflee** [comment]
Sorry about that. I recently went through all of the github repo settings and locked them down, including checking "Restrict editing to collaborators only: Public wikis will still be readable by everyone."

I just checked it, so @scootergrisen you can go ahead and edit the wiki if you'd wish.

**Pull request merged**
